name: lasuite

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    # always do this, except if a PR is triggered by DecapCMS
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, 'cms-bot')
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint sources
        run: yarn lint
      - name: Format sources
        run: yarn format
      - name: Build sources
        run: yarn build
  lint-git:
    runs-on: ubuntu-latest
    steps:
      - name: Report lint-git status
        run: echo "OK"
